// This file is autogenerated, see utils/generate_layout.py

#pragma once

#include <mbed.h>

% for name, kc in all_keycodes.items():
#define ${name} 0x${f'{kc:04X}'}
% endfor

struct matrix_loc_t {
    uint8_t r;
    uint8_t c;
};

struct led_loc_t {
    uint8_t driver;
    uint8_t r;
    uint8_t g;
    uint8_t b;
};

const uint16_t indexToKeycode[${len(index_to_keycode)}][105] = {
% for layer in index_to_keycode:
    { ${', '.join(f'0x{kc:04X}' for kc in layer)} },
% endfor
};

const uint8_t keycodeToIndex[256] = {
    ${', '.join(f'{idx}' for idx in keycode_to_index)}
};

const uint8_t matrixToIndex[8][16] = {
% for r in matrix_to_index:
    { ${', '.join(f'{c}' for c in r)} },
% endfor
};

const led_loc_t indexToLed[105] = {
    ${', '.join(f'{{ 0x{ll.d:02X}, 0x{ll.r:02X}, 0x{ll.g:02X}, 0x{ll.b:02X} }}' for ll in index_to_led)}
};

const uint8_t keyCount = ${len(key_map)};
